version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/python:3.8  # Use the appropriate base image for your project
    working_directory: ~/repo

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout  # Checkout the code from the repository
      - run:
          name: Set up Docker environment
          command: |
            sudo apt-get update
            sudo apt-get install -y docker.io
      - run:
          name: Build Docker Image
          command: |
            docker build -t your-docker-image:latest .  # Build the Docker image
      - run:
          name: Log in to Docker Hub
          command: |
            echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin  # Login using CircleCI environment variables
      - run:
          name: Push Docker Image
          command: |
            docker push your-docker-image:latest  # Push the Docker image to the registry

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
