name: CI Pipeline
on:
  push:
    branches:
      - main

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js Environment
    - name: Set Up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    # Step 3: Install Dependencies
    - name: Install Dependencies
      run: |
        npm install

    # Step 4: Run Linter
    - name: Lint the Code
      run: |
        npm run lint

    # Step 5: Build Docker Image
    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/react-app:latest .

    # Step 6: Scan Docker Image with Trivy
    - name: Scan Docker Image for Vulnerabilities
      uses: aquasecurity/trivy-action@latest
      with:
        image-ref: ${{ secrets.DOCKER_USERNAME }}/react-app:latest

    # Step 7: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 8: Push Docker Image to Docker Hub
    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/react-app:latest
